### ISSUE TITLE
Build Local Groups HTML Skeleton

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#10]
Below are the mocks that are mostly final for the local events page. We can build them out statically first and then next week we'll worry about connecting them to templates inside Craft. The static page for this is in `/public/assets/theme/events.html`.

![mobile-layout](https://cloud.githubusercontent.com/assets/779882/25209997/fbf6a838-254b-11e7-8960-26aa54b49208.png)

![local-group-desktop](https://cloud.githubusercontent.com/assets/779882/25210000/ffba931c-254b-11e7-896f-b2cb4b467117.png)

Prioritize building the mobile layout first, then we'll figure out how to scale it up. Here's an overview of [mobile first development](https://getflywheel.com/layout/start-practicing-mobile-first-development/) if you aren't familiar with the principles. Reach out in slack as well, we can talk it through. The main thing to know is that initial styling should be for the mobile design, and then media queries should be overrides for larger sizes.

There's a tablet width version here: 

![local-grouptablet portrait](https://cloud.githubusercontent.com/assets/779882/25558169/e254eef8-2cee-11e7-8792-eaf592a916e5.png)

**Comment by acolangelo** [comment]
For clarification: the designs here look to be for the District Maps page (1.1 in the [sitemap](https://drive.google.com/file/d/0B0l1jPto76PXTVV6WlJMYnBiaFE/view)), not the events page. Looks like there are other issues for the events pages (#14, #15), so this one is probably meant to be focused on District Maps?

**Comment by wnstn** [comment]
@acolangelo I do believe you're right, sorry about the confusion.

**Comment by wnstn** [comment]
@acolangelo actually despite the nav saying District Maps, this page is actually the Local Groups page. Feel free to create a `local-groups.html` page in the `public/assets/theme/` directory to build it out if you work on it.

**Comment by acolangelo** [comment]
Beautiful, thanks! Gonna get moving on that.
