### ISSUE TITLE
Craft: Event Filtering Should Only Show options if there are Events

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#105]
Not sure if this is possible or not, but the ideal functionality would be Local Groups would only be in the dropdown if they had an available event.

**Comment by wnstn** [comment]
I'm not sure this is easy to do, and I kind of think it's better UX wise for all groups to be selectable. That way users can filter to their group and see no events, rather that confusingly not seeing their group? What do you think  @sarawb ?

**Comment by sarawb** [comment]
The problem is just that we get a ton of null results -- more than half of local groups won't have an event at a given time. If this can't be changed I suppose it's fine, but I think UX-wise, selecting an option from a filter list sets an expectation that there will be something there.

**Comment by wnstn** [comment]
What if we provide messaging for empty results... something like "There are no events matching your search" expand your search etc etc.

**Comment by sarawb** [comment]
Yeah ok, that can work -- how about just, "Sorry, no events match your search right now." I don't want to say "expand" just because there's not really a lot to expand.
