### ISSUE TITLE
Browser Support Requirements

### ISSUE THREAD

**Issue by RyKilleen** [FDPA/fdpa#11]
As we build we'll want to know what we should be aiming for / testing in.

Pure CSS support is a solid base:

- IE 8+
- Latest Stable: Firefox, Chrome, Safari
- iOS 6-8
- Android 4.x 

Thoughts:

IE 11+ and evergreen browsers for desktop / mobile seems like a sane default.

**Comment by wnstn** [comment]
I'm +1 for IE11+ and evergreen browsers. I'll make sure we test on Android Firefox/Chrome as those can sometimes be strange but I'm not sure we'll be doing anything too complicated.

**Comment by onebrightlight** [comment]
Fantastic. I'm in the IE 11 camp too. Maybe brake sure we use polyfills for anything we add after the fact.
