### ISSUE TITLE
Build Form Styles

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#12]
We have a tentative design of form styles for the Join Form, these styles once approved will be our global form styles. Whomever loves to style inputs can go to town. I've created a `public/assets/css/form.css` file for working in, html can be built in `/public/assets/theme/form.html`. [Here's a brief reminder of form accessibility](http://webaim.org/techniques/forms/) if you want it.

![join-form-desktop](https://cloud.githubusercontent.com/assets/779882/25246317/4500e1f4-25d5-11e7-8ae4-15955f2d99c9.png)

Notice this second screenshot also includes an error state.

![join-form-desktop checked 1](https://cloud.githubusercontent.com/assets/779882/25246328/4e160b20-25d5-11e7-9526-25b37d5556bc.png)

**Comment by sarahbreiding** [comment]
I can work on this one

**Comment by wnstn** [comment]
We don't have a design for it yet, but there we'll be a form on the site that has a Datepicker, we'll probably use [Pikaday](https://github.com/dbushell/Pikaday).
