### ISSUE TITLE
Local Resolution PDFs are returning 404

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#133]
Craft thinks the PDF lives here http://107.170.57.118/assets/uploads/resolutions/Bethlehem-Township.pdf

But that link is 404. This is true of all PDFs.

**Comment by alexroper** [comment]
I think this is a deploy problem. PDFs were uploaded at one point but now they're gone.

**Comment by wnstn** [comment]
@alexroper confirming your deploy updates fixed this.
