### ISSUE TITLE
Create options for preferred event format field

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#147]
Need radio options (locked down for me) for preferred event format

30-minute talk
1-hour talk 
Small-group discussion
Panel discussion

**Comment by alexroper** [comment]
Are you talking about the field called "Preferred format/length of FDPA Program with Q&A?" Is this field part of a form yet?

**Comment by sarawb** [comment]
Yes, that's the one. It's been relabeled in the Request a Speaker page, but I cannot change the field type from plain text to radio options because Type is read-only for me.

![image](https://cloud.githubusercontent.com/assets/3171996/26357437/3aaf9fb0-3f9d-11e7-9b75-42f20aac8f1a.png)
