### ISSUE TITLE
Build Featured Events Module

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#15]
The top of the Events page has a Featured events module, if you just have an hour or two this might be a good snippet to build. The HTML should go at the top of `/public/assets/theme/events.html` and the CSS should go in the corresponding `events.css` file.

I imagine on mobile these will collapse down to be one column, although we'll have designs on that soon.

![image](https://cloud.githubusercontent.com/assets/779882/25246934/3e7d9618-25d7-11e7-9f44-523ecc89a5b1.png)

**Comment by alexroper** [comment]
Hey @wnstn, how are the featured events chosen? Do admins pick them manually? Or should it be the next upcoming event for a region (western, central and eastern)?

Is 3 the max number of features?

If they are manually chosen, but the even has ended, we could possibly pull recent events automatically to fill the space.

**Comment by wnstn** [comment]
@alexroper Sorry for my delay in answering. I think in an ideal case it's both; Admins can pick them manually or they default to the next upcoming event for a region. If that's too complicated I think we can default to the next event for a region, but @sarawb should confirm.

3 is definitely the max. Your final sentence makes sense to me.

**Comment by wnstn** [comment]
@esopp here is the mobile version of this since I forgot to add it to the ticket.

![image](https://cloud.githubusercontent.com/assets/779882/25558125/2efe883c-2cee-11e7-8bc7-ad259ad34aec.png)

**Comment by esopp** [comment]
Thanks @wnstn! I'm basically finished with desktop and mobile, just commenting on/organizing my code today, and waiting on icon svgs (partially my own fault because I didn't realize I should try asking for them in a direct message until I started writing this response).
