### ISSUE TITLE
Global color values

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#151]
- It looks like all the hex colors are a little off (maybe from grabbing them with a eyedropper?). Double check against the hex values from the palette artboard in Sketch (also pasted here) and ask @jasonsantamaria if questions
- Link underlines color should match link colors (they are a slightly brighter orange) 
![image](https://cloud.githubusercontent.com/assets/3171996/26226173/ca83d15e-3bf8-11e7-8748-892331f8d12d.png)
![image](https://cloud.githubusercontent.com/assets/3171996/26226210/079ba878-3bf9-11e7-860c-ae88345c3d09.png)

**Comment by alexroper** [comment]
Hmmm... in the CSS file there's notes at the top about colors. It lists these...

```
  Global Color Palette

  Green:      #89C65E
  Red:        #EF6851
  Orange:     #d27155
  Light Blue: #00645E
  Light Gray: #D8D8D8
  Med Blue:   #005149
  Med Gray:   #777
  Dark Blue:  #004642
  Dark Black: #333
``` 

Looks like orange should be #EF6851 and there's no red...

The links are set to that orange color (#d27155) and visited active and focused links are slightly darker #b15f47.

**Comment by alexroper** [comment]
Okay, I removed the 'red' color reference and changed all the orange to #EF6851.

I also removed the "visited" link colors so all the links should be the same orange now.

Let me know if you want to tweak the hover state for orange links. Currently the color on those is #b15f47.

**Comment by sarawb** [comment]
This all looks good to me!

**Comment by jasonsantamaria** [comment]
👍
