### ISSUE TITLE
Local Groups listing page styling 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#152]
Some design tweaks from Jason: 

- To make the lists a little less horsey, reduce the size of the type (I'd just suggest text size)
- Drop in the images Yesenia made of the state slices at the top of each column for a little visual interest

![image](https://cloud.githubusercontent.com/assets/3171996/26226261/5a28f2d0-3bf9-11e7-8109-9dec673a780d.png)

**Comment by esopp** [comment]
@sarawb I'm proceeding on the assumption that the icon should be part of the title/header of each column (e.g., "Western PA [icon]"), but should it actually appear centered OVER the columns (more like the green checkmarks on the homepage)?

**Comment by sarawb** [comment]
👍
