### ISSUE TITLE
Homepage styling tweaks

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#153]
Homepage tweaks from Jason: 
- Text with X bullets should be #666 not #333
- Blurbs under subheads should be #666 not #333
- Green check marks should use check marks from the design rather than unicode checks (Let me know if you need an svg)
- Bipartisan text below illo should be 20px and #666 rather than 18px and #333
-  "See What's Next" button label should be all caps, bold, and letterspaced out
- Three blurbs under "We Need You Now" should be #666 rather than #333

**Comment by esopp** [comment]
I can take this one, but an svg for the check marks would be much appreciated!

**Comment by esopp** [comment]
Oh, except I think the modification of the "See What's Next" button label has to be done from the admin account (which is to say, I can modify the element after the fact with javascript, but it seems like an unnecessarily convoluted way to go about things)? In which case, I don't have access at present.

**Comment by alexroper** [comment]
I think all of these have been fixed now.

**Comment by sarawb** [comment]
Yep, I think so! Closing out.
