### ISSUE TITLE
Endorsing organizations styling 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#154]
We need to style this page to increase the size of the logos and make the org names less horsey.

Two ideas from Jason: 
1. Make it a single column list, put the logos to the left.
2. Reduce the size of the type for the org names and add a significant gutter between the columns. 

However, I am wondering about a third option: since we have so many logos that are v horizontal, should we stack the logo and org name instead? If we did that, and reduce the org name text size, we could probably stay as 2-column while giving the logos a lot more prominence?

**Comment by esopp** [comment]
@sarawb could we eliminate the text anchor altogether and just use the logos, kind of like on the current/old page? (and then give each logo an alt description for screen-reader purposes?)

**Comment by sarawb** [comment]
I'd strongly prefer keeping the organization names in there -- it's much harder to skim logos and not all logos are clear about what the organization is.
