### ISSUE TITLE
Desktop masthead styling tweaks

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#156]
- Nav label "How We'll Fix It" needs a smart apostrophe
- Top right secondary links should be 14px and semibold rather than 16px
- "Join Us" button label should be all caps and letterspaced out
- A little less space above the logo and a little more below it (refer to comp)
- Main nav labels should align on the angle of the bottom of the logo (refer to comp)
- Footer social links should use the icons from the comps and be a little larger
- Is it possible to keep the masthead uncollapsed on tablet sizes like we specced? Not required, but I wanted to ask. I realize it's a lot to cram in there.
- On larger screens the masthead slant breaks down (see: https://cl.ly/3U2R3p1C3D3W). Not a dealbreaker, just wanted to call it out in case there is an easy fix.

**Comment by alexroper** [comment]
Some of these have already been tweaked. Try refreshing you browser to clear the cache.

- "Join Us" button label should be all caps (but not letterspaced out)
- Main nav labels should align on the angle of the bottom of the logo

**Comment by alexroper** [comment]
> On larger screens the masthead slant breaks down

I've managed to fix this up until the browser is around 3000px wide. Then a different bug pops up. the bottom right side of the slant gets cut off and turns flat. I think that's as good as we're going to get tho.

See #161 for the rest.

**Comment by alexroper** [comment]
Forgot to mention, I can add styles for a table sized masthead. There are layouts in the original Sketch files that adjusts the sizes of everything down a little bit.

It's probably a lower priority, tho, so we can revisit this.
