### ISSUE TITLE
Desktop subnav tweaks

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#157]
On interior page subnavs: 
- In order to consolidate spacing, let's ditch the full underline and just use underlines for active/on states. 
- Text should be 14px rather than 16px. 
- Remove the bg color from hover states. 
- For the on states, keep the text regular rather than semibold. 
- Remove the left margin from the section name at the start of the list.

**Comment by alexroper** [comment]
Take a look at the site and see if the new styles work.

![screen shot 2017-05-22 at 11 44 47 pm](https://cloud.githubusercontent.com/assets/377542/26341443/b2318116-3f48-11e7-8fde-256765683d02.png)

![screen shot 2017-05-22 at 11 44 58 pm](https://cloud.githubusercontent.com/assets/377542/26341448/b5500c50-3f48-11e7-9a67-f9467bc21a3f.png)
