### ISSUE TITLE
Legislator lookup styling tweaks

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#169]
- Remove "Type your Address to Search for your Pennsylvania Representatives" and change label to just "Address" 
- Lookup is pulling DE, NJ, NY addresses as well as PA -- should just pull up PA: 
![image](https://cloud.githubusercontent.com/assets/3171996/26280426/86a6282e-3da1-11e7-93b2-07b2db724fe4.png)
- Make email address for reps `mailto` link 
- Add a header before address that says "Mailing address" 
- Instead of "Visit their site to find local offices." have hypertext on link just say "Visit their website" (no period at the end)

**Comment by sarawb** [comment]
Also, we have some visual imbalance here, where we have "Representatives found for..." between the button and the actual results. Can we...
- Move that down below the button, right before the actual results 
- Change the wording to Your representatives 
- Put that into an H3, and then make the PA senate/house label an H4 and the person's name H5 

![image](https://cloud.githubusercontent.com/assets/3171996/26280456/06f21d20-3da3-11e7-8e05-a3386e078d2d.png)

**Comment by wnstn** [comment]
So looking at the docs, it seems to pull from a generalized region based on your IP. That is why our neighboring states show up. We can limit the range but IP is very inexact and so we might remove accurate results in the process. I can keep digging in the docs but it seems like range from IP might give us the most accurate results right now.

**Comment by sarawb** [comment]
Ok, we can leave as is. Can we address the rest of the styling/hierarchy stuff?

**Comment by wnstn** [comment]
Closing, this is all done so far as I can see.
