### ISSUE TITLE
Volunteer form - local group None error

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#170]
In the Volunteer form, users need to select a local group or select "None" if they don't have one. 

Currently, None is in the drop-down menu but selecting it throws an error on submission. We need to make this an allowed answer. 

![image](https://cloud.githubusercontent.com/assets/3171996/26284386/b874a57c-3e07-11e7-8326-dcd7bdb1a8ac.png)

**Comment by alexroper** [comment]
I made this field not required in the Volunteer Form.

Here's how to change this in Craft. In the form builder, click the field you want to edit, then uncheck the "This field is required?" checkbox.

![screen shot 2017-05-22 at 2 51 53 am](https://cloud.githubusercontent.com/assets/377542/26302643/c1c7103c-3e99-11e7-8a7b-d9c4480c80d7.png)

**Comment by sarawb** [comment]
Yeah, I set all the required fields. But we DO want them to fill this field out. We need people who have a local group to select it. We just also need None to be a valid option (or more accurately, "I don't live near any of these groups"). We want to avoid a ton of null entries.

**Comment by alexroper** [comment]
Oh, gotcha. Yes, we can make "none" have a valid value.

How about I make the first value "Select a local group" which is a null value, and make the last value something like "I don't live near any of these groups" and make that a valid response. Would that work?

**Comment by alexroper** [comment]
Also, sorry for pointing out obvious Craft features. I read this pretty late at night. Your original request went right over my head. :P

**Comment by sarawb** [comment]
No worries! I could easily have missed that field, too :) 

This works for me!

**Comment by sarawb** [comment]
Not sure what happened here but there's no option for those without a local group near them.

Can we also organize the local group dropdown by alpha?
