### ISSUE TITLE
Homepage - mobile: bottom CTAs out of alignment 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#175]
2nd and 3rd CTAs at the bottom are tabbed over on mobile: 

![image](https://cloud.githubusercontent.com/assets/3171996/26307423/6f4a7668-3ec2-11e7-89ac-16b7b2cc5e8f.png)

**Comment by alexroper** [comment]
Should be fixed by #176.

**Comment by sarawb** [comment]
👍 Closing out!
