### ISSUE TITLE
Craft CMS server requirements and PHP 7

### ISSUE THREAD

**Issue by alexroper** [FDPA/fdpa#18]
For whoever is setting up the staging server, here's list of the requirements for running Craft CMS:

https://craftcms.com/docs/requirements

Craft 2 only requires PHP 5.3, but I would highly recommend using PHP 7. Craft runs considerably faster on it and the next version of Craft 3 will require it.

The ImageMagick is extension would probably be handy to install also.

**Comment by wnstn** [comment]
@webolton I am closing this because I think it's all good but let me know if you know of anything else to do!
