### ISSUE TITLE
Freeform Errors are not output on page

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#208]
If the form has validation issues, we are not showing them. We should do that.

**Comment by sarawb** [comment]
Is this still an issue? I see we have these validation error messages showing: 

![image](https://user-images.githubusercontent.com/3171996/27016822-6806b756-4ef1-11e7-9fe9-5802017bd37b.png)

**Comment by sarawb** [comment]
@wnstn ^^^

**Comment by wnstn** [comment]
ak sorry, yeah, there is form validation and no other errors that seem to be accessible.
