### ISSUE TITLE
Event end time - make optional 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#212]
Right now, start and end are required - if you don't enter an end time, it defaults to 60 mins. 

For a lot of events, FDPA might be one of a few speakers and they don't know exactly what the timing will be, so they just want to say eg "6pm" and not "6-8pm". 

Is there a way to make is optional in the craft calendar?

**Comment by sarawb** [comment]
@wnstn can you look at this when you have a sec pls?

**Comment by alexroper** [comment]
According to the documentation, this is a required field of Solspace Calendar. 

https://solspace.com/craft/calendar/docs/events/

I tried setting the start and end time to the same value (6pm-6pm) and that just auto defaults to a 1 hour duration (6pm-7pm).

You may be able to ask Solspace support for a way to work around this or request this feature.

https://solspace.com/craft/create-ticket/calendar

**Comment by sarawb** [comment]
Thank you for researching! Submitted a ticket. I've had 3 complaints about this already, but I will politely dash their dreams if needed :)

**Comment by sarawb** [comment]
![image](https://user-images.githubusercontent.com/3171996/27201899-602d3556-51ed-11e7-8353-198221191fb3.png)

Sure okay. 

Is there any chance we could do something simple to just suppress _displaying_ the end time of an event on the front end if a box is checked in the form? 

If not, I'll tell them sorry but is what it is -- this is just an unexpectedly touchy issue with folks.

**Comment by alexroper** [comment]
Sure, we could probably add a checkbox for something like "Hide end time."

**Comment by sarawb** [comment]
This sounds like a great fix to me!

**Comment by alexroper** [comment]
I've added a new switch for "Hide end time" in the CMS. Here's a demo of an event I used it on:

https://staging.fairdistrictspa.com/events/2017/06/24/gerrymandering-what-it-is-why-it-matters-how-to-fix-it

username: staging
password: preview

If you want to try out the new setting, make sure to login to the control panel on the staging server, not the live server:

https://staging.fairdistrictspa.com

**Comment by sarawb** [comment]
👍 I think this is ready to go!
