### ISSUE TITLE
Additional event detail fields

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#218]
In Event listings, can we add optional fields for: 

**Contact information**
Name
Email
Phone

On the front end, this should display on the event detail page, under the Event Description, with its own subhead, like so: 

**CONTACT** 
Jane Doe
[jane@sample.com](mailto:jane@sample.com)  
(123) 456-7890

**Comment by alexroper** [comment]
Okay, I've added fields for Contact Name, Contact Phone, and Contact Email. Here's a demo of them in use on the staging server:

https://staging.fairdistrictspa.com/events/2017/06/24/gerrymandering-what-it-is-why-it-matters-how-to-fix-it

username: staging
password: preview

If this looks okay, I'll push it to the live site.

**Comment by sarawb** [comment]
👍 Looks great, thank you, @alexroper!
