### ISSUE TITLE
Join and Volunteer form updates (Action Network) 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#222]
Problem: Our Volunteer form collects Local Group, but that’s not a field in Action Network 

AN needs to get the field for local group added and populated with the local groups that are already on the website — Jean is researching this on her end and may ask for a hand. 

Once the field is added in AN, on our side we need to: 

- Map the field that we already have on our forms to this new custom field 
- Make this field part of Join, not just Volunteer, so all people who sign up have local group data
- Add a phone number field to Volunteer submissions only — (required or optional?)

**Comment by sarawb** [comment]
@wnstn it looks like Jean made the action network updates needed to be able to complete this. Phone number field should be optional. When do you think you can get this done? I know you're traveling this week.

**Comment by wnstn** [comment]
@sarawb Finally back from traveling, hope to have this knocked out tonight.

**Comment by wnstn** [comment]
@sarawb I don't see these updates from Jean so I'm going to respond to the email and get clarification.
