### ISSUE TITLE
Some event icons missing

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#227]
Some event icons are displaying in the local group page listings, some are not. Should probably all display.

![image](https://user-images.githubusercontent.com/3171996/27956229-cf39a524-62e6-11e7-86f4-7319f4ab1cf0.png)

**Comment by wnstn** [comment]
Fixed with this commit, deploying soon. https://github.com/FDPA/fdpa/commit/71b5b92a72e4dcab9fd7ad3b29f425a94e9df111

**Comment by sarawb** [comment]
👏
