### ISSUE TITLE
Event listings on local group pages - ability to see more than 3 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#231]
A couple active local groups have a lot of working sessions going, which means they often have more than the max of 3 upcoming events listed that will display on local group pages. Currently there is no link to the rest of the local events or even to the events calendar more generally. 

I think displaying more than 3 on the page will be problematic design-wise, so what I think we should do is:

- Add a link below the 3 surfaced events that says, "See all local events" (using the same style as the resolutions link we use below on that page)
- When a user clicks that link, send them to an event calendar filtered view showing all of that local group's events

I am up for other solutions if this doesn't work well.

**Comment by wnstn** [comment]
Deploying soon, this is added with https://github.com/FDPA/fdpa/commit/d4f2650b428caea3005b0dd7962e899c74735f91

**Comment by sarawb** [comment]
👌
