### ISSUE TITLE
Plugins aren't included on Cap Deploy

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#37]
I deployed master tonight, which had new plugins in `./craft/plugins` but they were not copied to the server. I had to manually sync them with `rsync`. I think this is not intended behavior as I couldn't find any setup that seemed to exclude these files.

**Comment by webolton** [comment]
I know what is wrong with this and will fix it tonight if I get a chance.

**Comment by webolton** [comment]
Kai. This should be fixed. For future reference, the application lives in /var/www/current.

If you have something that you can deploy, give it a try and let me know if you have trouble.
