### ISSUE TITLE
Body Matrix Macro

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#41]
The Body Matrix is what will be used for content of most content pages. The macro is [defined here](http://107.170.57.118/admin/settings/fields/edit/8).

Typical content page looks like this: 

![image](https://cloud.githubusercontent.com/assets/779882/25595318/512a59b8-2e92-11e7-8c7c-90bef0750e42.png)

**Comment by acolangelo** [comment]
Closing as dupe of #47.
