### ISSUE TITLE
Build Macro: Body Matrix Twig Template

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#47]
Here's the [setup for the matrix field](http://107.170.57.118/admin/settings/fields/edit/8)

It will be output on most pages, here's a general design.

![image](https://cloud.githubusercontent.com/assets/779882/25602243/41e5d9a4-2ec0-11e7-9995-22cc5177bb3c.png)

**Comment by onebrightlight** [comment]
This is addressed in #66, though it's erroneously named, as we need to add the field to the pertinent pages, but it looks like a lot of them are empty templates, still?
