### ISSUE TITLE
Local Groups Index Twig Template

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#48]
Here's the [field design for the local groups](http://107.170.57.118/admin/settings/sections/11/entrytypes/14).

Here's what the design will look like, althought `District Maps` will be replaced with the local group name.

![image](https://cloud.githubusercontent.com/assets/779882/25602697/e92a7a1e-2ec3-11e7-9661-d50b3af4fdcd.png)

**Comment by acolangelo** [comment]
@wnstn There’s a bit of overlap with this issue and #5. I may have this wrong, but seems like we should use #5 for the entry (which the design here is showing) and this one for the listing of local groups?

**Comment by wnstn** [comment]
Responding from mobile, I can clarify more after kids bed but go with what makes sense to you for now!

**Comment by acolangelo** [comment]
@wnstn thanks! Do we have a design for the local groups listing page? I haven’t been able to track one down just yet.
