### ISSUE TITLE
Map IA Document to Fields in every entry type

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#6]
We have a thorough Content and Functionality document here: https://docs.google.com/document/d/1DIpYrAl_P-te3iS-lqUIalKxFQI4G2aDkRP35DCGr0U/edit#heading=h.4zjeuygprfoq

This is the full functionality requirements based on [sitemap](https://drive.google.com/file/d/0B0l1jPto76PXTVV6WlJMYnBiaFE/view) and per [the outline](https://paper.dropbox.com/doc/FDPA-Notes-I9LmQu6y3RDzTJC1PDRWa) that the P&T people build for us.

We don't have a complete design mocks right now, but the content and functionality document should allow us to start making educated guesses for how to setup the fields in every content type.

**Comment by onebrightlight** [comment]
I'm happy to tackle the CMS implementation of fields and sections.

**Comment by onebrightlight** [comment]
Actually, I'll read the doc when I'm not mobile. I might get more insight. ;)

**Comment by onebrightlight** [comment]
Okay, so after digging through the Google Doc, it looks like we _do_ need fields created, yes? If that's the case, then I'm down for this chunk.

![](https://media0.giphy.com/media/3o6Mbjlo9YAoEtJJg4/giphy.gif)

**Comment by wnstn** [comment]
hey @onebrightlight I had a call with @alexroper earlier, I'm going to let y'all connect and strategize. I'll email in a minute, I have gotten access to some of our content pages to help you figure out what fields will be helpful.

Also, tomorrow we'll get access to the a&mForms plugin and Events plugin that will be used for the form pages and event calendar functionality. That should be the last pieces for Craft admin configuration.
