### ISSUE TITLE
Build out static version of homepage

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#61]
Emily to build out statically homepage; final content and illos are attached (only slightly different than last comp). 

Chris to build twig version. 

[(0.0) Home.txt](https://github.com/FDPA/fdpa/files/981938/0.0.Home.txt)
[FDPA-exported-images (1).zip](https://github.com/FDPA/fdpa/files/981939/FDPA-exported-images.1.zip)

**Comment by wnstn** [comment]
Addressed with #70
