### ISSUE TITLE
Craft content entry issues 

### ISSUE THREAD

**Issue by sarawb** [FDPA/fdpa#63]
*Pages that I cannot add in Craft - help needed*
- 9.0 Join (form page) - I can’t create this page because it’s top-level and that’s locked down 
- 4.2 Request a speaker (form page) - I don’t have a way to create a non-event-listing as a child to the Events page 
- 5.2 Start a group (form page) - Same issue; I can’t create a non-local-group page as a child to Local Groups 
- 6.2 Media Highlights - Have content, but it seems this needs to be created as another Single? Or as a Structure for About Subpages? Not sure, but I can’t create this page to enter content into it.

*Other*
- Image upload failing - directory doesn't exist - preventing image upload on Updates (blog) and content pages

**Comment by sarawb** [comment]
Note: got image upload working with @webolton last night. Those page creation items are where I still need Craft help.

**Comment by sarawb** [comment]
Looks like 9.0 Join has been built out by @alexroper.

**Comment by wnstn** [comment]
Closing this issue and moving to individual issues.
