### ISSUE TITLE
CSS: Homepage bullets need to be applied to The Problem page as well

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#82]
![image](https://cloud.githubusercontent.com/assets/779882/25913723/c5cea064-3589-11e7-995e-83ad02b92e3d.png)

Red X styles need to be applied to problem page as well.

**Comment by sarawb** [comment]
Since we have 2 types of bullets on that page and both can't be used, I think we are nixing this, yes? If so, let's close.

**Comment by sarawb** [comment]
Looks like this has been built into Craft, but resulting bullets aren't displaying on the front end (entire text is missing)

**Comment by esopp** [comment]
Not sure how helpful this actually is (as it probably isn't so very difficult to find the css) but for your convenience, the style for the red X bulleted list is in public/assets/css/index.css:
`.homepage-section-the-problem ul {
	padding: 0;
}

.homepage-section-the-problem ul > li {
	list-style: none;
	font-size: 19px;
	margin-bottom: 22px;
	padding-left: 35px;
	color: #666;
	position: relative;
}

.homepage-section-the-problem ul > li:before {
	content: "×";
	position: absolute;
	font-size: 55px;
	font-weight: bold;
	margin-right: 10px;
	color: #F66150;
	left: 0;
	top: -25px;
	background-color: transparent;
}`
