### ISSUE TITLE
Build Mobile Menu

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#9]
Mobile menu is a hamburger button that opens to a full screen menu. We'll want to include accessibility markup [as demonstrated in this demo](http://heydonworks.com/practical_aria_examples/#submenus) to ensure compatibility.

Menu and header looks like this:

![image](https://cloud.githubusercontent.com/assets/779882/25209838/684e4352-254b-11e7-92bc-225fa4de19f1.png)

Open state is like this:

![mobile-menu](https://cloud.githubusercontent.com/assets/779882/25209853/6e660fa4-254b-11e7-8db7-59e95cc5e844.png)

Let me know when actual SVG assets for the Logo/Menu button would be helpful, I'll try to get them ASAP.

Structure should be built in `/public/assets/theme/index.html`.

**Comment by esopp** [comment]
I can attempt this!

**Comment by esopp** [comment]
Hi @wnstn! No rush (especially since I have placeholders to work with) but I am approaching the point where the SVG assets for the menu would be useful.

**Comment by wnstn** [comment]
@esopp sorry for the delay, going to get you these assets this afternoon. Do you have a branch on github I could push them too?

**Comment by esopp** [comment]
Git thinks my user name is "localadmin," but I did create a branch (I had initially, incorrectly, just forked the master repository and cloned that):

feature/mobile-menu-main

**Comment by wnstn** [comment]
awesome, adding now!

**Comment by wnstn** [comment]
@esopp just pushed.

**Comment by esopp** [comment]
Thanks @wnstn! 
...and apologies for troubling you further, but is there an asset for the FDPA logo on the right side of the menu?

**Comment by wnstn** [comment]
@esopp so sorry for the delay on this. I've inquired with the designers and will get it to you ASAP.

**Comment by esopp** [comment]
It's okay! I realized I should inquire on the design channel on Slack, and Jason got it to me this morning.
