### ISSUE TITLE
Craft: Need to build way of tracking Legislators who cosponsor the legislation

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#90]
There's been discussion of this in Slack in #general, search to find it. Basic idea is we need something admin side (or a form visible publicly but not indexable by search engines) where FDPA can keep track of legislators that are supporting the legislation. This should be output on the Contact Your Legislator page as JSON. Another ticket will address the functionality of comparing this JSON to results from the find your legislator tool.

We also want to output this data as a list on Our Progress page, so data should probably involve district, house/senate, and name.

**Comment by sarawb** [comment]
We're not going to do this on account of it being too much. We'll just link to their google doc of co-sponsors.
