### ISSUE TITLE
Craft: Build Pass Resolutions functionality

### ISSUE THREAD

**Issue by wnstn** [FDPA/fdpa#95]
This is a list of links to PDFs with some descriptive text.

**Comment by alexroper** [comment]
This should be fixed now.

Sorry, I had updated the template code in the pull request, but hadn't made a change to the CMS yet.

To make this work I changed the Entry Type from "Take Action Subpage" to "Pass a Local Resolution."

<img width="351" alt="screen shot 2017-05-15 at 1 20 09 am" src="https://cloud.githubusercontent.com/assets/377542/26048628/cab90480-390c-11e7-83ce-6b2293e8fbae.png">

**Comment by wnstn** [comment]
Awesome!
